### ISSUE TITLE
Errors related to a mismatch between mh and opsworks

### ISSUE THREAD

**Issue by djcp** [harvard-dce/ec2-management#20]
So it seems like we get errors under at least two conditions:
- Instances have been started but not registered yet with MH (so while they're starting, or possibly if they've been started but shutdown before matterhorn was fully installed),

```
Nov  6 11:52:03 monitoring-master1 info: Traceback (most recent call last):
Nov  6 11:52:03 monitoring-master1 info:   File "./ec2_manager.py", line 138, in <module>
Nov  6 11:52:03 monitoring-master1 info:     cli()
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
Nov  6 11:52:03 monitoring-master1 info:     return self.main(*args, **kwargs)
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
Nov  6 11:52:03 monitoring-master1 info:     rv = self.invoke(ctx)
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1053, in invoke
Nov  6 11:52:03 monitoring-master1 info:     rv.append(sub_ctx.command.invoke(sub_ctx))
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
Nov  6 11:52:03 monitoring-master1 info:     return ctx.invoke(self.callback, **ctx.params)
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
Nov  6 11:52:03 monitoring-master1 info:     return callback(*args, **kwargs)
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_
func
Nov  6 11:52:03 monitoring-master1 info:     return f(get_current_context().obj, *args, **kwargs)
Nov  6 11:52:03 monitoring-master1 info:   File "./ec2_manager.py", line 26, in wrapped
Nov  6 11:52:03 monitoring-master1 info:     cmd(cluster, *args, **kwargs)
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 34, in wrapped
Nov  6 11:52:03 monitoring-master1 info:     return cmd(ec2, *args, **kwargs)
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 41, in wrapped
Nov  6 11:52:03 monitoring-master1 info:     result = cmd(ec2, *args, **kwargs)
Nov  6 11:52:03 monitoring-master1 info:   File "./ec2_manager.py", line 101, in autoscale
Nov  6 11:52:03 monitoring-master1 info:     cluster.autoscale()
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 528, in autoscale
Nov  6 11:52:03 monitoring-master1 info:     with self.in_maintenance(self.workers):
Nov  6 11:52:03 monitoring-master1 info:   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
Nov  6 11:52:03 monitoring-master1 info:     return self.gen.next()
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 675, in in_mainten
ance
Nov  6 11:52:03 monitoring-master1 info:     instances
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 674, in <lambda>
Nov  6 11:52:03 monitoring-master1 info:     lambda inst: self.is_running(inst) and not self.mh.is_in_maintenance(inst),
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/matterhorn.py", line 139, in is_
in_maintenance
Nov  6 11:52:03 monitoring-master1 info:     host = self.get_host_for_instance(inst)
Nov  6 11:52:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/matterhorn.py", line 135, in get
_host_for_instance
Nov  6 11:52:03 monitoring-master1 info:     "No Matterhorn host mappted to {}".format(inst.id)
```
- Instances exist only in opsworks and have not been started. 

```
InsecurePlatformWarning
Nov  6 14:00:03 monitoring-master1 info: Traceback (most recent call last):
Nov  6 14:00:03 monitoring-master1 info:   File "./ec2_manager.py", line 138, in <module>
Nov  6 14:00:03 monitoring-master1 info:     cli()
Nov  6 14:00:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
Nov  6 14:00:03 monitoring-master1 info:     return self.main(*args, **kwargs)
Nov  6 14:00:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
Nov  6 14:00:03 monitoring-master1 info:     rv = self.invoke(ctx)
Nov  6 14:00:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1053, in invoke
Nov  6 14:00:03 monitoring-master1 info:     rv.append(sub_ctx.command.invoke(sub_ctx))
Nov  6 14:00:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
Nov  6 14:00:03 monitoring-master1 info:     return ctx.invoke(self.callback, **ctx.params)
Nov  6 14:00:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
Nov  6 14:00:03 monitoring-master1 info:     return callback(*args, **kwargs)
Nov  6 14:00:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
Nov  6 14:00:03 monitoring-master1 info:     return f(get_current_context().obj, *args, **kwargs)
Nov  6 14:00:03 monitoring-master1 info:   File "./ec2_manager.py", line 26, in wrapped
Nov  6 14:00:03 monitoring-master1 info:     cmd(cluster, *args, **kwargs)
Nov  6 14:00:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 30, in wrapped
Nov  6 14:00:03 monitoring-master1 info:     if not ec2.admin_is_up():
Nov  6 14:00:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 175, in admin_is_up
Nov  6 14:00:03 monitoring-master1 info:     return self.is_running(self.admin_instance)
Nov  6 14:00:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 169, in admin_instance
Nov  6 14:00:03 monitoring-master1 info:     self._admin = next(x for x in self.instances if self.is_admin(x))
Nov  6 14:00:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/opsworks.py", line 71, in instances
Nov  6 14:00:03 monitoring-master1 info:     ops_inst = next(x for x in opsworks_instances if x['Ec2InstanceId'] == ec2_inst.id)
Nov  6 14:00:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/opsworks.py", line 71, in <genexpr>
Nov  6 14:00:03 monitoring-master1 info:     ops_inst = next(x for x in opsworks_instances if x['Ec2InstanceId'] == ec2_inst.id)
Nov  6 14:00:03 monitoring-master1 info: KeyError: 'Ec2InstanceId'
```

And then this error that I'm not entirely sure what spawned it:

```
Nov  6 10:54:03 monitoring-master1 info: Traceback (most recent call last):
Nov  6 10:54:03 monitoring-master1 info:   File "./ec2_manager.py", line 138, in <module>
Nov  6 10:54:03 monitoring-master1 info:     cli()
Nov  6 10:54:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
Nov  6 10:54:03 monitoring-master1 info:     return self.main(*args, **kwargs)
Nov  6 10:54:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
Nov  6 10:54:03 monitoring-master1 info:     rv = self.invoke(ctx)
Nov  6 10:54:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1053, in invoke
Nov  6 10:54:03 monitoring-master1 info:     rv.append(sub_ctx.command.invoke(sub_ctx))
Nov  6 10:54:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
Nov  6 10:54:03 monitoring-master1 info:     return ctx.invoke(self.callback, **ctx.params)
Nov  6 10:54:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
Nov  6 10:54:03 monitoring-master1 info:     return callback(*args, **kwargs)
Nov  6 10:54:03 monitoring-master1 info:   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
Nov  6 10:54:03 monitoring-master1 info:     return f(get_current_context().obj, *args, **kwargs)
Nov  6 10:54:03 monitoring-master1 info:   File "./ec2_manager.py", line 26, in wrapped
Nov  6 10:54:03 monitoring-master1 info:     cmd(cluster, *args, **kwargs)
Nov  6 10:54:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 33, in wrapped
Nov  6 10:54:03 monitoring-master1 info:     return cmd(ec2, *args, **kwargs)
Nov  6 10:54:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 39, in wrapped
Nov  6 10:54:03 monitoring-master1 info:     utils.log_status_summary(ec2.status_summary())
Nov  6 10:54:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/ec2.py", line 251, in status_summary
Nov  6 10:54:03 monitoring-master1 info:     inst_summary['maintenance'] = self.mh.is_in_maintenance(inst)
Nov  6 10:54:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/matterhorn.py", line 138, in is_in_maintenance
Nov  6 10:54:03 monitoring-master1 info:     host = self.get_host_for_instance(inst)
Nov  6 10:54:03 monitoring-master1 info:   File "/home/ec2_manager/ec2-management/controllers/matterhorn.py", line 129, in get_host_for_instance
Nov  6 10:54:03 monitoring-master1 info:     host_url = self.instance_host_map[inst.id]
Nov  6 10:54:03 monitoring-master1 info: KeyError: u'i-ad37f11d'
```

**Comment by djcp** [comment]
These errors don't appear in the opsworks mirror cluster, presumably because all the instances have been started (probably manually by me to "warm" them) and have registered themselves in the matterhorn UI.
